// PDF生成核心模块
// 使用Puppeteer渲染HTML生成PDF

export interface GenerateOptions {
  template: 'report' | 'invoice' | 'certificate';
  data: Record<string, any>;
  pageSize?: 'A4' | 'Letter' | 'A3';
  orientation?: 'portrait' | 'landscape';
}

export interface GenerateResult {
  success: boolean;
  pdf?: Buffer;
  error?: string;
}

// 生成报告模板HTML
function generateReportHTML(data: Record<string, any>): string {
  const items = data.items || [];
  const total = data.total || items.reduce((sum: number, item: any) => sum + (item.amount || 0), 0);
  
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@400;500;700&display=swap');
    
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: 'Noto Sans SC', 'PingFang SC', 'Microsoft YaHei', sans-serif;
      font-size: 14px;
      line-height: 1.6;
      color: #333;
      padding: 40px;
    }
    
    .header {
      text-align: center;
      margin-bottom: 40px;
      border-bottom: 2px solid #2563eb;
      padding-bottom: 20px;
    }
    
    .header h1 {
      font-size: 24px;
      color: #1e40af;
      margin-bottom: 8px;
    }
    
    .header .meta {
      font-size: 12px;
      color: #666;
    }
    
    .section {
      margin-bottom: 30px;
    }
    
    .section h2 {
      font-size: 16px;
      color: #1e40af;
      margin-bottom: 12px;
      padding-bottom: 8px;
      border-bottom: 1px solid #e5e7eb;
    }
    
    .summary {
      background: #f8fafc;
      padding: 16px;
      border-radius: 8px;
      margin-bottom: 20px;
    }
    
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 16px;
    }
    
    th, td {
      padding: 12px;
      text-align: left;
      border-bottom: 1px solid #e5e7eb;
    }
    
    th {
      background: #f1f5f9;
      font-weight: 600;
      color: #475569;
    }
    
    tr:hover {
      background: #f8fafc;
    }
    
    .text-right {
      text-align: right;
    }
    
    .total {
      margin-top: 20px;
      text-align: right;
      font-size: 18px;
      font-weight: 700;
      color: #2563eb;
    }
    
    .footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      text-align: center;
      font-size: 12px;
      color: #999;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${data.title || '报告'}</h1>
    <div class="meta">
      ${data.company || '公司名称'} | ${data.date || new Date().toLocaleDateString('zh-CN')}
    </div>
  </div>
  
  ${data.summary ? `
  <div class="section">
    <h2>摘要</h2>
    <div class="summary">${data.summary}</div>
  </div>
  ` : ''}
  
  ${items.length > 0 ? `
  <div class="section">
    <h2>详细数据</h2>
    <table>
      <thead>
        <tr>
          <th>名称</th>
          <th class="text-right">数量</th>
          <th class="text-right">金额</th>
        </tr>
      </thead>
      <tbody>
        ${items.map((item: any) => `
          <tr>
            <td>${item.name}</td>
            <td class="text-right">${item.quantity || 1}</td>
            <td class="text-right">¥${(item.amount || 0).toLocaleString()}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
    <div class="total">合计: ¥${total.toLocaleString()}</div>
  </div>
  ` : ''}
  
  ${data.content ? `
  <div class="section">
    <h2>内容</h2>
    <p>${data.content}</p>
  </div>
  ` : ''}
  
  <div class="footer">
    Generated by DocFlow | ${new Date().toLocaleString('zh-CN')}
  </div>
</body>
</html>
`;
}

// 生成发票模板HTML
function generateInvoiceHTML(data: Record<string, any>): string {
  const items = data.items || [];
  const total = data.total || items.reduce((sum: number, item: any) => sum + (item.amount || 0), 0);
  const invoiceNumber = data.invoiceNumber || `INV-${Date.now()}`;
  
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@400;500;700&display=swap');
    
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: 'Noto Sans SC', 'PingFang SC', 'Microsoft YaHei', sans-serif;
      font-size: 14px;
      line-height: 1.6;
      color: #333;
      padding: 40px;
    }
    
    .invoice-header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      margin-bottom: 40px;
      padding-bottom: 20px;
      border-bottom: 3px solid #059669;
    }
    
    .invoice-title {
      font-size: 32px;
      font-weight: 700;
      color: #059669;
      letter-spacing: 4px;
    }
    
    .invoice-meta {
      text-align: right;
      font-size: 12px;
      color: #666;
    }
    
    .invoice-meta .number {
      font-size: 14px;
      font-weight: 600;
      color: #333;
      margin-bottom: 4px;
    }
    
    .parties {
      display: flex;
      justify-content: space-between;
      margin-bottom: 40px;
    }
    
    .party {
      width: 45%;
    }
    
    .party-label {
      font-size: 12px;
      font-weight: 600;
      color: #059669;
      text-transform: uppercase;
      margin-bottom: 8px;
    }
    
    .party-name {
      font-size: 16px;
      font-weight: 700;
      margin-bottom: 4px;
    }
    
    .party-detail {
      font-size: 12px;
      color: #666;
    }
    
    table {
      width: 100%;
      border-collapse: collapse;
      margin-bottom: 30px;
    }
    
    th, td {
      padding: 14px 12px;
      text-align: left;
      border-bottom: 1px solid #e5e7eb;
    }
    
    th {
      background: #f0fdf4;
      font-weight: 600;
      color: #166534;
    }
    
    .text-right {
      text-align: right;
    }
    
    .text-center {
      text-align: center;
    }
    
    .total-section {
      display: flex;
      justify-content: flex-end;
    }
    
    .total-box {
      width: 280px;
      background: #059669;
      color: white;
      padding: 20px;
      border-radius: 8px;
    }
    
    .total-label {
      font-size: 14px;
      opacity: 0.9;
    }
    
    .total-amount {
      font-size: 28px;
      font-weight: 700;
    }
    
    .footer {
      margin-top: 60px;
      text-align: center;
      font-size: 12px;
      color: #999;
    }
    
    .status {
      display: inline-block;
      background: #059669;
      color: white;
      padding: 4px 12px;
      border-radius: 4px;
      font-size: 12px;
      font-weight: 600;
    }
  </style>
</head>
<body>
  <div class="invoice-header">
    <div>
      <div class="invoice-title">发票</div>
      <div style="font-size: 12px; color: #666; margin-top: 4px;">INVOICE</div>
    </div>
    <div class="invoice-meta">
      <div class="number">#${invoiceNumber}</div>
      <div>日期: ${data.date || new Date().toLocaleDateString('zh-CN')}</div>
      <div style="margin-top: 8px;"><span class="status">已支付</span></div>
    </div>
  </div>
  
  <div class="parties">
    <div class="party">
      <div class="party-label">开票方</div>
      <div class="party-name">${data.fromName || data.company || '示例公司'}</div>
      <div class="party-detail">${data.fromAddress || '公司地址'}</div>
      <div class="party-detail">${data.fromEmail || 'email@example.com'}</div>
    </div>
    <div class="party">
      <div class="party-label">收票方</div>
      <div class="party-name">${data.toName || '客户名称'}</div>
      <div class="party-detail">${data.toAddress || '客户地址'}</div>
      <div class="party-detail">${data.toEmail || 'customer@example.com'}</div>
    </div>
  </div>
  
  <table>
    <thead>
      <tr>
        <th>项目描述</th>
        <th class="text-center">数量</th>
        <th class="text-right">单价</th>
        <th class="text-right">金额</th>
      </tr>
    </thead>
    <tbody>
      ${items.length > 0 ? items.map((item: any, index: number) => `
        <tr>
          <td>${item.name || `项目 ${index + 1}`}</td>
          <td class="text-center">${item.quantity || 1}</td>
          <td class="text-right">¥${(item.price || item.amount || 0).toLocaleString()}</td>
          <td class="text-right">¥${(item.amount || (item.price || 0) * (item.quantity || 1)).toLocaleString()}</td>
        </tr>
      `).join('') : `
        <tr>
          <td>${data.description || '服务/产品'}</td>
          <td class="text-center">1</td>
          <td class="text-right">¥${total.toLocaleString()}</td>
          <td class="text-right">¥${total.toLocaleString()}</td>
        </tr>
      `}
    </tbody>
  </table>
  
  <div class="total-section">
    <div class="total-box">
      <div class="total-label">总计 (人民币)</div>
      <div class="total-amount">¥${total.toLocaleString()}</div>
    </div>
  </div>
  
  <div class="footer">
    Generated by DocFlow | 如有疑问请联系开票方
  </div>
</body>
</html>
`;
}

// 生成证书模板HTML
function generateCertificateHTML(data: Record<string, any>): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@400;500;700&display=swap');
    
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: 'Noto Sans SC', 'PingFang SC', 'Microsoft YaHei', sans-serif;
      font-size: 14px;
      line-height: 1.8;
      color: #333;
      padding: 60px;
      display: flex;
      justify-content: center;
      align-items: center;
      min-height: 100vh;
    }
    
    .certificate {
      width: 100%;
      max-width: 800px;
      border: 12px double #b45309;
      padding: 60px;
      position: relative;
      background: linear-gradient(135deg, #fffbeb 0%, #fef3c7 100%);
    }
    
    .corner {
      position: absolute;
      width: 60px;
      height: 60px;
      border: 3px solid #b45309;
    }
    
    .corner-tl { top: 20px; left: 20px; border-right: none; border-bottom: none; }
    .corner-tr { top: 20px; right: 20px; border-left: none; border-bottom: none; }
    .corner-bl { bottom: 20px; left: 20px; border-right: none; border-top: none; }
    .corner-br { bottom: 20px; right: 20px; border-left: none; border-top: none; }
    
    .header {
      text-align: center;
      margin-bottom: 30px;
    }
    
    .emblem {
      font-size: 48px;
      margin-bottom: 10px;
    }
    
    .title {
      font-size: 36px;
      font-weight: 700;
      color: #b45309;
      letter-spacing: 8px;
      margin-bottom: 8px;
    }
    
    .subtitle {
      font-size: 14px;
      color: #92400e;
      letter-spacing: 4px;
    }
    
    .content {
      text-align: center;
      margin: 40px 0;
    }
    
    .presented-to {
      font-size: 14px;
      color: #666;
      margin-bottom: 16px;
    }
    
    .recipient {
      font-size: 42px;
      font-weight: 700;
      color: #1e40af;
      margin-bottom: 20px;
      padding-bottom: 10px;
      border-bottom: 2px solid #e5e7eb;
      display: inline-block;
    }
    
    .reason {
      font-size: 18px;
      color: #374151;
      margin-bottom: 20px;
      line-height: 1.8;
    }
    
    .reason-text {
      background: white;
      padding: 20px 40px;
      border-radius: 8px;
      display: inline-block;
      border: 1px solid #fde68a;
    }
    
    .footer {
      display: flex;
      justify-content: space-between;
      align-items: flex-end;
      margin-top: 50px;
    }
    
    .date, .signature {
      text-align: center;
    }
    
    .date-value, .company-value {
      font-size: 16px;
      font-weight: 600;
      color: #374151;
    }
    
    .date-label, .company-label {
      font-size: 12px;
      color: #666;
      margin-bottom: 8px;
    }
    
    .seal {
      width: 80px;
      height: 80px;
      border: 3px solid #dc2626;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      color: #dc2626;
      font-size: 12px;
      font-weight: 700;
      transform: rotate(-15deg);
    }
    
    .footer-note {
      text-align: center;
      margin-top: 40px;
      font-size: 11px;
      color: #999;
    }
  </style>
</head>
<body>
  <div class="certificate">
    <div class="corner corner-tl"></div>
    <div class="corner corner-tr"></div>
    <div class="corner corner-bl"></div>
    <div class="corner corner-br"></div>
    
    <div class="header">
      <div class="emblem">🏆</div>
      <div class="title">荣誉证书</div>
      <div class="subtitle">CERTIFICATE OF HONOR</div>
    </div>
    
    <div class="content">
      <div class="presented-to">授予</div>
      <div class="recipient">${data.recipient || '获得者姓名'}</div>
      <div class="reason">
        <div class="reason-text">
          ${data.reason || data.description || '荣获此荣誉，特发此证'}
        </div>
      </div>
    </div>
    
    <div class="footer">
      <div class="date">
        <div class="date-label">日期</div>
        <div class="date-value">${data.date || new Date().toLocaleDateString('zh-CN', { year: 'numeric', month: 'long', day: 'numeric' })}</div>
      </div>
      <div class="seal">官方<br>印章</div>
      <div class="signature">
        <div class="company-label">颁发单位</div>
        <div class="company-value">${data.issuer || data.company || '公司名称'}</div>
      </div>
    </div>
    
    <div class="footer-note">
      此证书由 DocFlow 生成 | 证书编号: ${data.certificateNumber || `CERT-${Date.now()}`}
    </div>
  </div>
</body>
</html>
`;
}

// 根据模板生成HTML
function generateHTML(options: GenerateOptions): string {
  switch (options.template) {
    case 'invoice':
      return generateInvoiceHTML(options.data);
    case 'certificate':
      return generateCertificateHTML(options.data);
    case 'report':
    default:
      return generateReportHTML(options.data);
  }
}

// 获取PDF页面尺寸
function getPageFormat(size: string): string {
  switch (size) {
    case 'Letter':
      return 'Letter';
    case 'A3':
      return 'A3';
    case 'A4':
    default:
      return 'A4';
  }
}

// 主生成函数
export async function generatePDF(options: GenerateOptions): Promise<GenerateResult> {
  try {
    // 动态导入Puppeteer以避免在非服务器环境报错
    const puppeteer = require('puppeteer');
    
    const html = generateHTML(options);
    
    const browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    });
    
    const page = await browser.newPage();
    
    await page.setContent(html, {
      waitUntil: 'networkidle0'
    });
    
    const pdf = await page.pdf({
      format: getPageFormat(options.pageSize || 'A4'),
      landscape: options.orientation === 'landscape',
      printBackground: true,
      margin: {
        top: '20px',
        right: '20px',
        bottom: '20px',
        left: '20px'
      }
    });
    
    await browser.close();
    
    return {
      success: true,
      pdf: Buffer.from(pdf)
    };
  } catch (error: any) {
    console.error('PDF generation error:', error);
    return {
      success: false,
      error: error.message || 'PDF生成失败'
    };
  }
}

export { generateHTML, generateReportHTML, generateInvoiceHTML, generateCertificateHTML };
